version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: petshop_postgres
    environment:
      POSTGRES_USER: petshop_user
      POSTGRES_PASSWORD: petshop_db_password_123!
      POSTGRES_DB: petshop_db
    ports:
      - "5432:5432"
    volumes:
      - petshop_pgdata:/var/lib/postgresql/data

volumes:
  petshop_pgdata:
